---
- name: Set host_uri for libvirt mode
  ansible.builtin.set_fact:
    host_uri: "qemu+ssh://{{ host }}/system"
  when:
    - mode == "libvirt"

- name: Display task inputs
  ansible.builtin.debug:
    msg:
      - "Inputs provided:"
      - "Host: {{ host }}"
      - "Mode: {{ mode }}"
      - "URI: {{ host_uri }}"
      - "VM to check: {{ vm_name }}"

# May need dnf install -y python3-lxml on the host
- name: Query host 
  community.libvirt.virt:
    command: status
    name: "{{ vm_name }}"
    uri: "{{ host_uri }}"
  register: virt_output
  when:
    - mode == "libvirt"

- name: Display raw vm_info structure
  ansible.builtin.debug:
    var: virt_output

