# Parameters that can be changed, or passed in. Hard coded for testing purposes.
  organisation: sjl_t10
  location: G8NET
  offered_os:
    - rhel8
    - rhel9
    - rhel10
  tenant_locations:
    - loc1
    - loc2
    - loc3
  promotion_paths:
    - canary
    - test
    - prod
    - dev

# Split out.
#function update_hostgroup () {
#}

#function create_lifecycle_env () {
#}

  - name: Find organisation
    block:
      - name: Get organisation info
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - organization
            - info
            - --name
            - {{ organisation }}
        become: yes
        register: organisation_data
    rescue: # The organisation doesn't exist
      - name: Create organisation
        hosts: satellite
        ansible.builtin.command:
          argv:
            - hammer
            - organization
            - create
            - --name
            - {{ organisation }}

      - name: Retrieve new organisation info
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - organization
            - info
            - --name
            - {{ organisation }}
        become: yes
        register: organisation_data
    always:
      - name: Register organisation ID
        organisation_id: {{ organisation_data.stdout | community.general.json_query('Id') }}

  - name: Find location
    block:
      - name: Get location info
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - location
            - info
            - --name
            - {{ location }}
        become: yes
        register: location_data
    rescue: # The organisation doesn't exist
      - name: Create location
        hosts: satellite
        ansible.builtin.command:
          argv:
            - hammer
            - location
            - create
            - --name
            - {{ location }}

      - name: Retrieve new organisation info
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - location
            - info
            - --name
            - {{ location }}
        become: yes
        register: location_data
    always:
      - name: Register location ID
        location_id: {{ location_data.stdout | community.general.json_query('Id') }}

  - name: Get the Library LCE ID
    hosts: satellite
    ansible.builtin.command:
      argv:
        - /usr/bin/hammer
        - --output
        - json
        - lifecycle-environment
        - info
        - --name
        - Library
    become: yes
    register: library_data
    library_lce_id: {{ library_data.stdout | community.general.json_query('Id') }}

# Check for the environment path: we want two streams. Stream one is Library -> lce_infra.
# Stream two is Library -> lce_canary -> lce_test -> lce_prod -> lce_dev.
# Note that the LCE name must be unique within an organisation, so if one of those
# already exists, we assume that it's in the right position in the stream.

  # lce_infra is its own thing.
  - name: Create the infra lifecycle environment
    create_lifecycle_environment:
      lifecycle_env_name: "lce_infra"
      organisation: {{ organisation }}
      previous_id: {{ library_lce_id }}
    infra_lce_id: # XXX

  previous_lce_id: {{ library_lce_id }}
  all_lce_ids:
    - {{ infra_lce_id }}
    - {{ library_lce_id }}

  - name: Create the main environment path
    create_lifecycle_environment:
      lifecycle_env_name: "lce_{{ item }}"
      organisation: {{ organisation }}
      previous_id: {{ previous_lce_id }}
    previous_id: # XXX
    all_lce_ids:
      - {{ all_lce_ids }}
      - {{ previous_id }}
    lce_path_ids:
      - {{ lce_path_ids }}
      - {{ previous_id }}
    loop: {{ promotion_paths }}



# Split out.
# Parameters:
#   $1 - the operating system (rhel8, rhel9, rhel94, etc.)
#   $2 - the organisation ID
#   $3 - the architecture (defaults to x86_64 if not specified)
#function build_repo_list () {
#}

# Now that we have the environment paths: look for and validate the content views.
  - name: Create the content views
# Loop through the operating systems that we want to offer.
for tier1_hg_os in ${OFFERED_OS[*]}; do
  # Check whether a content view for the OS exists. If it doesn't, create it, and apply the
  # desired filters.
  cv_id_str=`hammer content-view info --name cv_$tier1_hg_os --organization-id $org_id --fields id`
  if [ -z "$cv_id_str" ]; then
    # Attempt to add the repositories in. Note that this requires a subscription
    # manifest. If we created the organisation, there won't be a manifest, so there
    # won't be any repositories.
    repo_list=`build_repo_list $tier1_hg_os $org_id x86_64`
    if [ -z "$repo_list" ]; then
      repo_param=""
    else
      repo_param="--repository-ids ${repo_list}"
    fi
    hammer content-view create --name cv_$tier1_hg_os --organization-id $org_id --auto-publish false $repo_param
    cv_id_str=`hammer content-view info --name cv_$tier1_hg_os --organization-id $org_id --fields id`
    cv_os_id=`echo $cv_id_str|sed -e 's+^Id: ++'`

    # Create the filters. There might be no repositories, but we create the filters anyway so that
    # the framework is in place.

    # First, the RPM filter.
    hammer content-view filter create --content-view-id $cv_os_id --inclusion true --name filter_noerrata --organization-id $org_id --original-packages true --type rpm

    # Second, the errata filter and rule.
    hammer content-view filter create --content-view-id $cv_os_id --inclusion true --name filter_periodically_updates --organization-id $org_id --type erratum
    cvf_id_str=`hammer content-view filter info --content-view-id $cv_os_id --fields 'filter id' --name filter_periodically_updates --organization-id $org_id`
    cvf_id=`echo $cvf_id_str|sed -e 's+^Filter ID: ++'`
    # XXX: Defaults to today. Is this correct?
    hammer content-view filter rule create --content-view-filter-id $cvf_id --content-view-id $cv_os_id --end-date `date -I` --organization-id $org_id --types enhancement,bugfix,security

    # XXX: Do we need to publish a version before we proceed? - yes.
    hammer content-view publish --id $cv_os_id --organization-id $org_id --lifecycle-environments $all_lce_ids

    # And now forcibly promote it to all the LCEs, because we can't associate an LCE if it doesn't have the CV version.
    for lce_id in ${lce_path_ids[*]}; do
      hammer content-view version promote --content-view-id $cv_os_id --from-lifecycle-environment-id $lib_lce_id --to-lifecycle-environment-id $lce_id --organization-id $org_id
    done
  fi
  cv_os_id=`echo $cv_id_str|sed -e 's+^Id: ++'`

  # For each operating system, create a hg-OS. LCE at this level is Library.
  # The hg_OS group might already exist in a different organisation, in which
  # case, extend it to our organisation.
  str_hg_id=`hammer hostgroup info --title hg_$tier1_hg_os --fields id`
  if [ -z "$str_hg_id" ]; then
    hammer hostgroup create --name hg_$tier1_hg_os --organization-id $org_id --lifecycle-environment-id $lib_lce_id --content-view-id $cv_os_id --location-id $loc_id
    str_hg_id=`hammer hostgroup info --title hg_$tier1_hg_os --fields id`
  else
    update_hostgroup hg_$tier1_hg_os $org_id $loc_id
  fi

  parent_name=hg_$tier1_hg_os

  # Derive the ID number from the string hammer returned
  hg_os_id=`echo $str_hg_id|sed -e 's+^Id: ++'`

  # Now create the nested location hostgroups for each operating system.
  for tier2_hg_loc in ${TENANT_LOCS[*]}; do
    id=`hammer hostgroup info --title $parent_name/hg_$tier2_hg_loc --fields id`
    if [ -z "$id" ]; then
      # Once again, lifecycle environment is Library at this level.
      hammer hostgroup create --name hg_$tier2_hg_loc --lifecycle-environment-id $lib_lce_id --location-id $loc_id --organization-id $org_id --parent-id $hg_os_id
      id=`hammer hostgroup info --title $parent_name/hg_$tier2_hg_loc --fields id`
    else
      update_hostgroup $parent_name/hg_$tier2_hg_loc $org_id $loc_id
    fi

    hg_loc_id=`echo $id|sed -e 's+^Id: ++'`
    loc_parent_name=$parent_name/hg_$tier2_hg_loc

    # Lastly: promotion paths. Tier 3.
    for count in ${!PROMOTION_PATHS[@]}; do
      tier3_hg_name=hg_${PROMOTION_PATHS[$count]}
      # Find the LCE, if it exists.
      lce_id=${lce_path_ids[$count]}
      if [ -z "$lce_id" ]; then
        echo "Couldn't find the LCE ID for ${PROMOTION_PATHS[$count]} - we shouldn't be here.."
        # Create, or default? For now: default
        lce_id=$lib_lce_id
      fi
      
      id=`hammer hostgroup info --title $loc_parent_name/$tier3_hg_name --fields id`
      if [ -z "$id" ]; then
        hammer hostgroup create --name $tier3_hg_name --lifecycle-environment-id $lce_id --location-id $loc_id --organization-id $org_id --parent-id $hg_loc_id
      else
        update_hostgroup $loc_parent_name/$tier3_hg_name $org_id $loc_id
      fi
    done
  done
done
    loop: {{ offered_os }}

