# For a single operating system, find/create the content view (and filters),
# attempt to add in repositories if we're creating, promote to lifecycle
# environments, create the OS-level host group, and then loop through for
# the second tier (location) hostgroups. We don't handle the third tier
# here - that's in the second tier functionality.

  # Check whether a content view for the OS exists. If it doesn't, create it, and apply the
  # desired filters.
  - name: Find or create the content view
    block:
      - name: Get content view info
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - info
            - --name
            - "cv_{{ tier1_hg_os }}"
            - --organization-id
            - {{ organisation_id }}
        become: yes
        register: cv_data
    rescue:
      - name: Get the repositories if they exist
        # XXX: call out to build_repository_list.yaml

      - name: Create the content view without repositories
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - create
            - --name
            - "cv_{{ tier1_hg_os }}"
            - --organization-id
            - {{ organisation_id }}
            - --auto-publish
            - false
        become: yes
        register: cv_data
        when: repo_list == ""

      - name: Create the content view with repositories
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - create
            - --name
            - "cv_{{ tier1_hg_os }}"
            - --organization-id
            - {{ organisation_id }}
            - --auto-publish
            - false
            - --repository-ids
            - {{ repo_list }}
        become: yes
        register: cv_data
        when: repo_list != ""

      - name: Register the new content view ID
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - info
            - --name
            - "cv_{{ tier1_hg_os }}"
            - --organization-id
            - {{ organisation_id }}
        become: yes
        register: cv_data

      - name: Create the RPM filter
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - filter
            - create
            - --name
            - filter_noerrata
            - --organization-id
            - {{ organisation_id }}
            - --inclusion
            - true
            - --content-view-id
            - {{ cv_data.stdout | community.general.json_query('Id') }}
            - --original-packages
            - true
            - --type
            - rpm
        become: yes

      - name: Create the errata filter
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - filter
            - create
            - --name
            - filter_periodically_updates
            - --organization-id
            - {{ organisation_id }}
            - --inclusion
            - true
            - --content-view-id
            - {{ cv_data.stdout | community.general.json_query('Id') }}
            - --type
            - erratum
        become: yes

      - name: Register the errata filter ID
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - filter
            - info
            - --name
            - filter_periodically_updates
            - --organization-id
            - {{ organisation_id }}
            - --content-view-id
            - {{ cv_data.stdout | community.general.json_query('Id') }}
        become: yes
        register: filter_info

      - name: Create the errata filter rule
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - filter
            - rule
            - create
            - --content-view-filter-id
            - {{ filter_info.stdout | community.general.json_query('Filter ID') }}
            - --content-view-id
            - {{ cv_data.stdout | community.general.json_query('Id') }}
            - --end-date
            - ansible_date_time.date
            - --organization-id
            - {{ organisation_id }}
            - --types
            - enhancement,bugfix,security
    #cv_id_str=`hammer content-view info --name cv_$tier1_hg_os --organization-id $org_id --fields id`
    #cv_os_id=`echo $cv_id_str|sed -e 's+^Id: ++'`

      - name: Publish the content view
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - publish
            - --id
            - {{ cv_data.stdout | community.general.json_query('Id') }}
            - --organization-id
            - {{ organisation_id }}
            - --lifecycle-environments
            - # XXX all_lce_ids

      - name: Force promote the newly published content view
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - content-view
            - version
            - promote
            - --content-view-id
            - {{ cv_data.stdout | community.general.json_query('Id') }}
            - --organization-id
            - {{ organisation_id }}
            - --from-lifecycle-environment-id
            - {{ library_lce_id }}
            - --to-lifecycle-environment-id
            - {{ item }}
        loop: {{ lce_path_ids }}

  - name: Register the content view ID
    cv_id: {{ cv_data.stdout | community.general.json_query('Id') }}

  # For each operating system, create a hg-OS. LCE at this level is Library.
  # The hg_OS group might already exist in a different organisation, in which
  # case, extend it to our organisation.
  - name: Look for or create the host group
    block:
      - name: Obtain data for existing host group
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - hostgroup
            - info
            - --title
            - "hg_{{ tier1_hg_os }}"
        register: host_group_data
      - name: Update existing host group
        # XXX Call update_hostgroup
        #update_hostgroup hg_$tier1_hg_os $org_id $loc_id
    rescue: # Doesn't exist, so let's create it.
      - name: Create the missing host group
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - hostgroup
            - create
            - --name
            - "hg_{{ tier1_hg_os }}"
            - --organization-id
            - {{ organisation_id }}
            - --lifecycle-environment-id
            - {{ lib_lce_id }}
            - --content-view-id
            - {{ cv_id }}
            - --location-id
            - {{ location_id }}
      - name: Register the host group data
        hosts: satellite
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - hostgroup
            - info
            - --title
            - "hg_{{ tier1_hg_os }}"
        register: host_group_data
    always:
      - name: Retrieve the host group ID
        hg_os_id: {{ host_group_data | community.general.json_query('Id') }}

  #parent_name=hg_$tier1_hg_os

  # Now create the nested location hostgroups for each operating system.
  - name: Create second tier hostgroups
    # XXX: Call tier2_loop.yaml
    loop: {{ tenant_locations }}
