# Code to create a single tier 3 host group. This is expected
# to be called as part of a loop during the tier 2 host group
# creation process.

  - name: Find or create the promotion path
    # tier3_hg_name
    # path_lce_id
    # parent_name
    # location_id
    # parent_id
    # organisation_id
    block:
      - name: Find the host group
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - hostgroup
            - info
            - --title
            - "{{ parent_name }}/{{ tier3_hg_name }}"
        become: yes
        register: tier3_hg_data
      - name: Update the host group
        # Call out to the update_hostgroup YAML.
    rescue: # The host group doesn't exist.
      - name: Create the host group
        ansible.builtin.command:
          argv:
            - /usr/bin/hammer
            - --output
            - json
            - hostgroup
            - create
            - --name
            - {{ tier3_hg_name }}
            - --lifecycle-environment-id
            - {{ path_lce_id }}
            - --location-id
            - {{ location_id }}
            - --organization-id
            - {{ organisation_id }}
            - --parent-id
            - {{ parent_id }}
