---
- name: Query repository set
  command: >
    hammer repository-set show
    --organization-id "{{ organization_id }}"
    --product "{{ product }}"
    --name "{{ repository }}"
  register: repo_set
  changed_when: false

- name: Check if repository is enabled
  set_fact:
    repo_enabled: "{{ '1)' in repo_set.stdout }}"

- name: Enable repository set if not already enabled
  command: >
    hammer repository-set enable
    --organization-id "{{ organization_id }}"
    --product "{{ product }}"
    --basearch x86_64
    --releasever {{ releasever }}
    --name "{{ repository }}"
  register: enable_result
  when:
    - product != "Fedora EPEL"
    - not repo_enabled

- name: Re-query repository set to capture repo name
  command: >
    hammer repository-set show
    --organization-id "{{ organization_id }}"
    --product "{{ product }}"
    --name "{{ repository }}"
  register: repo_set_with_reponame
  changed_when: false
  when:
    - product != "Fedora EPEL"

- name: Extract enabled repository name or for non-RH Repos like EPEL use reposet as the repository
  set_fact:
    enabled_repository: "{{ repo_set_with_reponame.stdout | regex_findall('(?m)^\\s*Name:\\s*(.+)$') | last | default(repository) }}"

- name: Synchronize repository
  command: >
    hammer repository synchronize
    --organization-id "{{ organization_id }}"
    --product "{{ product }}"
    --name "{{ enabled_repository }}"
  when: do_sync | bool

- name: Lookup content view current repos
  command: >
    hammer content-view info --fields "Yum repositories/name"
    --organization-id "{{ organization_id }}"
    --name "{{ cv }}"
  register: content_view_current_repos 
  changed_when: false
  # Output captured in content_view_current_repos might look something like this:
  # Yum Repositories:
  # 1) Name: Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs
  # 2) Name: Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9
  # 3) Name: Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9
  # For simplicity, rather than output it to a json and scan the array, we grep

- name: Determine if Repo Needs to be Added to Content View
  set_fact:
    # This creates a simple boolean we use to drive subsequent behavior
    repo_already_present: "{{ enabled_repository in content_view_current_repos.stdout }}"

- name: Lookup repository for its ID
  command: >
    hammer --output json repository info 
    --organization-id "{{ organization_id }}"
    --product "{{ product }}"
    --name "{{ enabled_repository }}"
  changed_when: false
  register: repoid_lookup 
  when: not repo_already_present

- name: Extract repository ID
  set_fact:
    repo_id: "{{ (repoid_lookup.stdout | from_json).Id }}"
  changed_when: false
  when: not repo_already_present

- name: Ensure our repo is set in the Content View
  command: >
    hammer content-view add-repository 
    --name "{{ cv }}"
    --organization-id "{{ organization_id }}"
    --repository-id "{{ repo_id }}"
  when: not repo_already_present

