---
# -----------------------------------------------------------------------------
# Look for repositories that we can add to the content view.
# -----------------------------------------------------------------------------
- name: Lookup base OS RPM repository
  command:
    argv:
      - hammer
      - --output
      - json
      - repository
      - info
      - --name
      - "{{ os_name }} - BaseOS RPMs {{ os_version }}"
      - --organization-id
      - "{{ organization_id }}"
      - --product
      - "{{ product_name }}"
  register: base_os_repo_lookup
  failed_when: false
  changed_when: false

- name: Create empty repository ID list
  set_fact:
    repo_list: [ ]

- name: Add base OS RPM repository ID to list
  set_fact:
    repo_list: "{{ repo_list }} + [ {{ (base_os_repo_lookup.stdout | from_jason).Id }} ]"
    when: base_os_repo_lookup.rc == 0

- name: Lookup appstream RPM repository
  command:
    argv:
      - hammer
      - --output
      - json
      - repository
      - info
      - --name
      - "{{ os_name }} - AppStream RPMs {{ os_version }}"
      - --organization-id
      - "{{ organization_id }}"
      - --product
      - "{{ product_name }}"
  register: appstream_repo_lookup
  failed_when: false
  changed_when: false

- name: Add appstream RPM repository ID to list
  set_fact:
    repo_list: "{{ repo_list }} + [ {{ (appstream_repo_lookup.stdout | from_jason).Id }} ]"
    when: appstream_repo_lookup.rc == 0

- name: Lookup Satellite client repository
  command:
    argv:
      - hammer
      - --output
      - json
      - repository
      - info
      - --name
      - "Red Hat Satellite Client 6 for RHEL {{ os_version }} {{ arch }} RPMs"
      - --organization-id
      - "{{ organization_id }}"
      - --product
      - "{{ product_name }}"
  register: satellite_repo_lookup
  failed_when: false
  changed_when: false

- name: Add Satellite client repository ID to list
  set_fact:
    repo_list: "{{ repo_list }} + [ {{ (satellite_repo_lookup.stdout | from_jason).Id }} ]"
    when: satellite_repo_lookup.rc == 0
